Sprint5
ClevertecFrontendLab/VitalyHanchar pull request #3
Opened 2023-03-09 16:25 UTC by VitalyHanchar

2023-03-09 20:25 UTC, Ivan6813 requested changes

2023-03-09 20:25 UTC, Ivan6813 commented on src/components/forms/form-register-step1.jsx
> +  numbers: (value) => /[0-9]{1,}/.test(value),
на 17 строке эта регулярка повторяется. Вообще все регулярки можно вынести в константы и дать им понятные названия, так будет лучше читабельность кода

2023-03-09 20:25 UTC, Ivan6813 commented on src/components/forms/form-register-step1.jsx
> +};
а в чем плюс описывать так типы? может стоит использовать TypeScript для этого?

2023-03-09 20:25 UTC, Ivan6813 commented on src/components/forms/form-register-step3.jsx
> +                '+',
вынеси эту маску в константу, так выглядит не очень

2023-03-09 20:25 UTC, Ivan6813 commented on src/components/forms/form-reset-password.jsx
> +};
кажется это повторялось выше - повод задуматься о переиспользовании

2023-03-09 20:25 UTC, Ivan6813 commented on src/components/loading/loading.jsx
> +// );
закомментированного кода быть не должно

2023-03-09 20:25 UTC, Ivan6813 commented on src/pages/registration/registration.jsx
> +            <Button size='large' onClick={() => navigate('/auth')}>
кажется здесь было бы уместно использовать Link, использовать так navigate не очень правильно

2023-03-09 20:25 UTC, Ivan6813 commented on src/redux/sagas/user.js
> +    // yield delay(1000);
и тут закомментированный код

2023-03-09 23:12 UTC, VitalyHanchar commented on src/components/forms/form-register-step1.jsx
> +};
В документе к первому заданию было прямо жирным выделено было что будет плюсом использование TS или PropsTypes. Польза от него в том, что в консоль выводятся сообщения о несоответствии типов или об отсутствии обязательного параметра. Что касается TS я не могу его использовать так как не владею данным языком. На начало тренинга я и с React дела не имел, а параллельно изучать TS и React решил, что не потяну. Я сам крайне удивлён что дошёл аж до сюда.

2023-03-09 23:17 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 95%.
Общее количество тестов: 20.
Количество непройденных тестов: 1.
***
**authorization and registartion -- password recovery -- forgot password validation (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678403838/authorization%20and%20registartion%20--%20password%20recovery%20--%20forgot%20password%20validation%20(failed).png)
***
**error reset password.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678403838/error%20reset%20password.png)
***
**first enter.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678403838/first%20enter.png)
***
**incorrect logit or password error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678403838/incorrect%20logit%20or%20password%20error.png)
***
**loader authorization.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678403838/loader%20authorization.png)
***
**password hidden.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678403838/password%20hidden.png)
***
**password shown.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678403838/password%20shown.png)
***
**recovery page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678403838/recovery%20page.png)
***
**registration already used error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678403838/registration%20already%20used%20error.png)
***
**registration error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678403838/registration%20error.png)
***
**registration page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678403838/registration%20page.png)
***
**registration-first-step.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678403838/registration-first-step.png)
***
**registration-second-step.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678403838/registration-second-step.png)
***
**registration-success.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678403838/registration-success.png)
***
**registration-third-step.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678403838/registration-third-step.png)
***
**send email error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678403838/send%20email%20error.png)
***
**send email success.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678403838/send%20email%20success.png)
***
**server error authorization.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678403838/server%20error%20authorization.png)
***
**success reset password.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678403838/success%20reset%20password.png)

2023-03-10 06:44 UTC, Ivan6813 approved these changes

2023-03-10 06:44 UTC, Ivan6813 commented on src/components/layout/layout.jsx
> +  useEffect(() => {}, [dispatch]);
такой useEffect стоит вообще удалить, он же ничего не делает

2023-03-10 08:02 UTC, merged