Sprint6
ClevertecFrontendLab/VitalyHanchar pull request #4
Opened 2023-03-16 18:01 UTC by VitalyHanchar

2023-03-16 18:05 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 84%.
Общее количество тестов: 25.
Количество непройденных тестов: 4.
***
**10-selected-day.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678989911/10-selected-day.png)
***
**11-booking-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678989911/11-booking-error.png)
***
**12-booking-success.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678989911/12-booking-success.png)
***
**13-booking-edit-modal-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678989911/13-booking-edit-modal-view.png)
***
**14-modal-edited-date.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678989911/14-modal-edited-date.png)
***
**15-rate-modal.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678989911/15-rate-modal.png)
***
**16-rate-modal-mobile.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678989911/16-rate-modal-mobile.png)
***
**17-rate-filled.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678989911/17-rate-filled.png)
***
**18-comments-updated-sort.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678989911/18-comments-updated-sort.png)
***
**2-booking-modal-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678989911/2-booking-modal-view.png)
***
**3-mobile-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678989911/3-mobile-view.png)
***
**4-january.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678989911/4-january.png)
***
**5-december-2022.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678989911/5-december-2022.png)
***
**6-february.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678989911/6-february.png)
***
**7-today-is-friday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678989911/7-today-is-friday.png)
***
**8-today-is-saturday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678989911/8-today-is-saturday.png)
***
**9-today-is-sunday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678989911/9-today-is-sunday.png)
***
**booking and book rate -- booking buttons view -- check booking button active (no user) (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678989911/booking%20and%20book%20rate%20--%20booking%20buttons%20view%20--%20check%20booking%20button%20active%20(no%20user)%20(failed).png)
***
**booking and book rate -- booking buttons view -- check booking button disabled (already booked) (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678989911/booking%20and%20book%20rate%20--%20booking%20buttons%20view%20--%20check%20booking%20button%20disabled%20(already%20booked)%20(failed).png)
***
**booking and book rate -- booking buttons view -- check booking button disabled (on delivery) (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678989911/booking%20and%20book%20rate%20--%20booking%20buttons%20view%20--%20check%20booking%20button%20disabled%20(on%20delivery)%20(failed).png)
***
**booking and book rate -- booking buttons view -- check booking edit button active (booked by current user) (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678989911/booking%20and%20book%20rate%20--%20booking%20buttons%20view%20--%20check%20booking%20edit%20button%20active%20(booked%20by%20current%20user)%20(failed).png)
***
**edit-mobile-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1678989911/edit-mobile-view.png)

2023-03-16 20:53 UTC, graffad requested changes

2023-03-16 20:53 UTC, graffad commented on src/components/button/button.jsx
> +      type={type === 'button' ? 'button' : 'submit'}
тип по умолчанию уже задан в defaultProps, сюда достаточно просто type

2023-03-16 20:53 UTC, graffad commented on src/components/modals/booking-modal.jsx
> +          {/* {booking ? 'Изменить дату бронирования' : 'забронировать'} */}
удалить коммент

2023-03-16 20:53 UTC, graffad commented on src/pages/book/book-page.jsx
> +                    {/* {book.booking ? `Занята до ${getDate(book.booking.dateOrder)}` : 'Забронировать'} */}
удалить комменты

2023-03-16 20:53 UTC, graffad commented on src/redux/sagas/booking.js
> +    if (error?.response.status === 400) {
ну тогда бы на 500+ отправлял другое сообщение, а то оно одинаковое и теряется смысл проверки. Достаточно yield put(openToastSlice(toastBookingsErrorMsg));

2023-03-16 20:53 UTC, graffad commented on src/components/modals/booking-modal.jsx
> +        <input type='hidden' {...register('data.order', { value: true })} />
ну это в принципе можно в саге достать с select и пришить к запросу вместо hidden, ок пусть остается

2023-03-16 20:53 UTC, graffad commented on src/components/toast/toast.jsx
> +    }, 4000);
лучше добавить очистку таймаута и массив зависимости

2023-03-16 22:40 UTC, VitalyHanchar commented on src/redux/sagas/booking.js
> +    if (error?.response.status === 400) {
Сперва решил, что надо на 400 код другое сообщение показывать, а потом понял, что сообщения в макете и то что ожидает увидеть в тесте это разные сообщения. И про лишний код который успел накидать благополучно забыл)

2023-03-16 22:40 UTC, VitalyHanchar commented on src/components/button/button.jsx
>    const sizeClass = size === 'large' ? 'button--large' : '';
Secondary в основном по условию ставиться. Если переделать таким образом придётся вызывать как view={isBooking ? 'secondary': 'primary'}

2023-03-16 22:40 UTC, VitalyHanchar commented on src/components/button/button.jsx
> +      type={type === 'button' ? 'button' : 'submit'}
Написал так что бы линтер не ругался) Исправил.

2023-03-16 22:45 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 25.
Количество непройденных тестов: 0.
***
**1-all-buttons.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1679006728/1-all-buttons.png)
***
**10-selected-day.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1679006728/10-selected-day.png)
***
**11-booking-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1679006728/11-booking-error.png)
***
**12-booking-success.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1679006728/12-booking-success.png)
***
**13-booking-edit-modal-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1679006728/13-booking-edit-modal-view.png)
***
**14-modal-edited-date.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1679006728/14-modal-edited-date.png)
***
**15-rate-modal.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1679006728/15-rate-modal.png)
***
**16-rate-modal-mobile.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1679006728/16-rate-modal-mobile.png)
***
**17-rate-filled.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1679006728/17-rate-filled.png)
***
**18-comments-updated-sort.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1679006728/18-comments-updated-sort.png)
***
**2-booking-modal-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1679006728/2-booking-modal-view.png)
***
**3-mobile-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1679006728/3-mobile-view.png)
***
**4-january.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1679006728/4-january.png)
***
**5-december-2022.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1679006728/5-december-2022.png)
***
**6-february.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1679006728/6-february.png)
***
**7-today-is-friday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1679006728/7-today-is-friday.png)
***
**8-today-is-saturday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1679006728/8-today-is-saturday.png)
***
**9-today-is-sunday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1679006728/9-today-is-sunday.png)
***
**edit-mobile-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/VitalyHanchar/1679006728/edit-mobile-view.png)

2023-03-17 07:16 UTC, graffad approved these changes

2023-03-17 08:32 UTC, merged